apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-agent-config
  namespace: voice-agent
data:
  VOICE_AGENT_INTERNAL_PORT: "3000"
  TRAEFIK_HOST_PORT: "8081"
  TRAEFIK_CONTAINER_PORT: "80"
  TRAEFIK_DASHBOARD_HOST_PORT: "8090"
  TRAEFIK_DASHBOARD_CONTAINER_PORT: "8080"
  NODE_ENV: "development"
